import './style.css';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),reduce=matchMedia('(prefers-reduced-motion: reduce)');
const W=1000,H=800,boatX=520,baseY=485; let phase='ready',round=0,start=0,best=Infinity,raf,audioOn=false,audio;
try{const n=Number(localStorage.getItem('la-ola-perfecta-best'));if(Number.isFinite(n)&&n>=0)best=n}catch{}
function rand(a,b){return a+Math.random()*(b-a)}
function newRound(){round++; phase='ready'; start=performance.now(); state={lambda:rand(460,620),amp:rand(45,64),speed:rand(150,210),crest0:rand(-180,-70)};$('round-label').textContent='OLA '+String(round).padStart(2,'0');$('ready').hidden=false;$('result').hidden=true;$('scene-label').textContent='TOCA JUSTO EN LA CRESTA';$('scene').classList.add('can-hit');}
let state;
function crest(t){return state.crest0+state.speed*t}
function nearestCrest(t){let c=crest(t),n=Math.round((boatX-c)/state.lambda);return c+n*state.lambda}
function waveY(x,t){return baseY-state.amp*Math.cos((Math.PI*2/state.lambda)*(x-crest(t)))}
function slope(x,t){let k=Math.PI*2/state.lambda;return state.amp*k*Math.sin(k*(x-crest(t)))}
function ping(perfect=false){if(!audioOn)return;try{audio??=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=perfect?660:330;g.gain.setValueAtTime(.055,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.13);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.14)}catch{}}
function celebrate(){if(reduce.matches)return;let l=$('scene-overlay');for(let i=0;i<24;i++){let p=document.createElement('i');p.className='confetti';p.style.left=(35+Math.random()*30)+'%';p.style.top=(30+Math.random()*20)+'%';p.style.setProperty('--dx',((Math.random()-.5)*260)+'px');p.style.setProperty('--dy',(90+Math.random()*160)+'px');l.append(p)}setTimeout(()=>l.replaceChildren(),1400)}
function track(){try{window.goatcounter?.count?.({path:'ronda-completada',title:'Ronda completada',event:true,no_session:true})}catch{}}
function hit(){if(phase!=='ready')return;let t=(performance.now()-start)/1000,c=nearestCrest(t),signed=boatX-c,d=Math.abs(signed);phase='result';let cat=d<8?'perfect':d<25?'near':d<60?'good':'far';$('verdict').textContent={perfect:'¡Ola perfecta!',near:'¡Casi perfecta!',good:'Buena ola.',far:'Fuera de cresta.'}[cat];$('distance').textContent=Math.round(d);$('side').textContent=d<1?'Justo en la cresta.':signed>0?'Tocaste un poco antes.':'Tocaste un poco después.';if(d<best){best=d;try{localStorage.setItem('la-ola-perfecta-best',String(best))}catch{}}$('best').textContent='MEJOR MARCA PERSONAL · '+Math.round(best)+' CM';$('ready').hidden=true;$('result').hidden=false;$('scene-label').textContent='OLA REGISTRADA';$('scene').classList.remove('can-hit');ping(cat==='perfect');if(cat==='perfect')celebrate();track()}
function path(points,fill){ctx.beginPath();ctx.moveTo(...points[0]);points.slice(1).forEach(p=>ctx.lineTo(...p));ctx.closePath();ctx.fillStyle=fill;ctx.fill()}
function draw(now){let t=(now-start)/1000;ctx.clearRect(0,0,W,H);let sky=ctx.createLinearGradient(0,0,0,520);sky.addColorStop(0,'#e9eee7');sky.addColorStop(.62,'#f3eee2');sky.addColorStop(1,'#e9dfcd');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(224,177,106,.3)';ctx.beginPath();ctx.arc(820,145,72,0,Math.PI*2);ctx.fill();
path([[0,370],[150,330],[260,350],[390,302],[520,346],[640,315],[760,350],[1000,310],[1000,470],[0,470]],'#b9c9ba');path([[0,410],[180,390],[330,425],[500,382],[700,420],[1000,375],[1000,500],[0,500]],'#8ca99d');
let pts=[];for(let x=0;x<=W;x+=10)pts.push([x,waveY(x,t)]);ctx.beginPath();ctx.moveTo(0,H);ctx.lineTo(0,pts[0][1]);pts.forEach(p=>ctx.lineTo(...p));ctx.lineTo(W,H);ctx.closePath();let sea=ctx.createLinearGradient(0,430,0,H);sea.addColorStop(0,'#6faaa2');sea.addColorStop(1,'#326f70');ctx.fillStyle=sea;ctx.fill();ctx.strokeStyle='#dbe8df';ctx.lineWidth=5;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();
let by=waveY(boatX,t)-34,ang=Math.atan(slope(boatX,t))*.42;ctx.save();ctx.translate(boatX,by);ctx.rotate(ang);ctx.fillStyle='rgba(25,62,61,.16)';ctx.beginPath();ctx.ellipse(0,34,72,10,0,0,Math.PI*2);ctx.fill();path([[-65,0],[65,0],[42,32],[-42,32]],'#f4ead8');ctx.strokeStyle='#315d5b';ctx.lineWidth=3;ctx.stroke();path([[-17,0],[-8,-35],[24,-35],[39,0]],'#bd6b50');ctx.fillStyle='#244c4d';ctx.fillRect(-4,-48,4,48);ctx.restore();requestAnimationFrame(draw)}
$('hit').onclick=hit;$('scene').onclick=hit;$('again').onclick=newRound;document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&phase==='ready'&&!$('bookmark-dialog').open){e.preventDefault();hit()}});
$('sound').onclick=()=>{audioOn=!audioOn;$('sound').setAttribute('aria-pressed',String(audioOn));$('sound-label').textContent=audioOn?'ON':'OFF';$('sound-icon').textContent=audioOn?'◖))':'◖̸';if(audioOn)ping(false)};
$('bookmark').onclick=()=>{$('bookmark-text').textContent=/iPhone|iPad/i.test(navigator.userAgent)?'En Safari, pulsa Compartir y elige «Añadir a favoritos».':'Pulsa Ctrl+D (Windows/Linux), ⌘+D (Mac) o usa el menú del navegador para guardar el juego.';$('bookmark-dialog').showModal()};
if(ctx){newRound();raf=requestAnimationFrame(draw)}else{$('scene-label').textContent='No se pudo iniciar la escena. Recarga la página.';$('hit').disabled=true}
