import './style.css';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),reduce=matchMedia('(prefers-reduced-motion: reduce)');
const W=1000,H=800;let phase='ready',streak=0,best=0,audioOn=false,audio,state,raf;
try{best=Number(localStorage.getItem('paso-entre-olas-best'))||0}catch{}
const rand=(a,b)=>a+Math.random()*(b-a);
function resetGate(){phase='ready';state={start:performance.now(),period:rand(2100,2850),offset:rand(0,Math.PI*2),launch:0,quality:0,boatY:650,impact:0};$('streak').textContent=streak;$('best-live').textContent=best;$('scene-label').textContent='ESPERA EL HUECO · TOCA PARA PASAR';$('action').disabled=false}
function gap(now){let t=(now-state.start)/state.period*Math.PI*2+state.offset;return 78+150*(.5+.5*Math.sin(t))}
function ping(ok){if(!audioOn)return;try{audio??=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=ok?620:180;g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.16);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.17)}catch{}}
function track(ok){try{window.goatcounter?.count?.({path:ok?'paso-superado':'partida-finalizada',title:ok?'Paso superado':'Partida finalizada',event:true,no_session:true})}catch{}}
function go(){if(phase!=='ready')return;let g=gap(performance.now()),q=Math.max(0,Math.min(1,(g-90)/105));state.quality=q;state.launch=performance.now();phase='crossing';$('action').disabled=true;$('scene-label').textContent=q>.58?'¡AHORA!':'¡DEMASIADO CERRADO!';ping(q>.58)}
function success(){streak++;if(streak>best){best=streak;try{localStorage.setItem('paso-entre-olas-best',String(best))}catch{}}$('streak').textContent=streak;$('best-live').textContent=best;$('scene-label').textContent='¡PASO LIMPIO! · RACHA '+streak;track(true);setTimeout(resetGate,620)}
function fail(){phase='gameover';state.impact=performance.now();$('final-streak').textContent=streak;$('final-best').textContent=Math.max(best,streak);$('gameover').hidden=false;$('hud').hidden=true;$('scene-label').textContent='LA OLA TE ALCANZÓ';track(false)}
function restart(){streak=0;$('gameover').hidden=true;$('hud').hidden=false;resetGate()}
function drawBoat(x,y,angle=0){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.fillStyle='rgba(22,65,66,.16)';ctx.beginPath();ctx.ellipse(0,34,62,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f4ead8';ctx.strokeStyle='#315d5b';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-58,0);ctx.lineTo(58,0);ctx.lineTo(36,30);ctx.lineTo(-38,30);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#bd6b50';ctx.fillRect(-15,-32,36,32);ctx.fillStyle='#244c4d';ctx.fillRect(-2,-45,4,45);ctx.restore()}
function waveWall(y,top,g,side){let edge=side==='left'?500-g/2:500+g/2;ctx.save();ctx.fillStyle='#397b79';ctx.strokeStyle='#e6f0e8';ctx.lineWidth=12;ctx.beginPath();if(side==='left'){ctx.moveTo(0,top);ctx.lineTo(edge-35,top);ctx.quadraticCurveTo(edge+22,top+45,edge-8,y);ctx.lineTo(0,y)}else{ctx.moveTo(W,top);ctx.lineTo(edge+35,top);ctx.quadraticCurveTo(edge-22,top+45,edge+8,y);ctx.lineTo(W,y)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
function draw(now){ctx.clearRect(0,0,W,H);let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#e8eee7');sky.addColorStop(.5,'#e8dfcf');sky.addColorStop(1,'#397b79');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(220,171,100,.3)';ctx.beginPath();ctx.arc(820,120,65,0,Math.PI*2);ctx.fill();ctx.fillStyle='#a9bdae';ctx.beginPath();ctx.moveTo(0,280);ctx.lineTo(160,245);ctx.lineTo(290,285);ctx.lineTo(430,235);ctx.lineTo(610,285);ctx.lineTo(790,250);ctx.lineTo(1000,285);ctx.lineTo(1000,350);ctx.lineTo(0,350);ctx.closePath();ctx.fill();ctx.fillStyle='#5f9b94';ctx.fillRect(0,340,W,H-340);
let g=gap(now);waveWall(525,335,g,'left');waveWall(525,335,g,'right');
ctx.save();ctx.setLineDash([8,10]);ctx.strokeStyle='rgba(248,242,218,.72)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(500-g/2,545);ctx.lineTo(500+g/2,545);ctx.stroke();ctx.restore();
let bx=500,by=650,ang=0;if(phase==='crossing'){let p=Math.min(1,(now-state.launch)/780);by=650-330*p;let safe=state.quality>.58;if(!safe&&p>.62){bx+=Math.sin((p-.62)*9)*80;ang=(p-.62)*2.2}ctx.fillStyle='rgba(245,250,244,.72)';for(let i=0;i<7;i++){ctx.beginPath();ctx.arc(bx-35+i*12,by+42+i%2*7,5+i*.5,0,Math.PI*2);ctx.fill()}if(p>=1){safe?success():fail()}}else if(phase==='gameover'){let p=Math.min(1,(now-state.impact)/600);bx=500+Math.sin(p*8)*65;by=445+p*40;ang=p*.8}
drawBoat(bx,by,ang);raf=requestAnimationFrame(draw)}
$('action').onclick=go;$('scene').onclick=e=>{if(e.target!==$('action'))go()};$('again').onclick=restart;document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&phase==='ready'&&!$('bookmark-dialog').open){e.preventDefault();go()}});
$('sound').onclick=()=>{audioOn=!audioOn;$('sound').setAttribute('aria-pressed',String(audioOn));$('sound-label').textContent=audioOn?'ON':'OFF';$('sound-icon').textContent=audioOn?'◖))':'◖̸'};
$('bookmark').onclick=()=>{$('bookmark-text').textContent=/iPhone|iPad/i.test(navigator.userAgent)?'En Safari, pulsa Compartir y elige «Añadir a favoritos».':'Pulsa Ctrl+D (Windows/Linux), ⌘+D (Mac) o usa el menú del navegador para guardar el juego.';$('bookmark-dialog').showModal()};
resetGate();raf=requestAnimationFrame(draw);