import './style.css';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),reduce=matchMedia('(prefers-reduced-motion: reduce)');
const W=1000,H=800,targetX=760;let phase='ready',best=null,audioOn=false,audio,state;
try{const n=Number(localStorage.getItem('el-amarre-perfecto-best'));if(Number.isFinite(n)&&n>=0)best=n}catch{}
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function newRound(){phase='ready';state={start:performance.now(),x:120,v:rand(155,205),drift:rand(-5,8),cutAt:0,stopX:0,resultAt:0};$('ready').hidden=false;$('result').hidden=true;$('scene-label').textContent='CORTA MOTOR Y DEJA QUE DESLICE';$('best').textContent=best===null?'MEJOR · —':'MEJOR · '+best.toFixed(2)+' M';}
function tone(perfect=false){if(!audioOn)return;try{audio??=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=perfect?650:360;g.gain.setValueAtTime(.055,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.19)}catch{}}
function cut(){if(phase!=='ready')return;phase='coast';state.cutAt=performance.now();$('scene-label').textContent='MOTOR CORTADO · ESPERA…';$('action').disabled=true}
function finish(){if(phase==='result')return;phase='result';state.resultAt=performance.now();let err=Math.abs(targetX-state.x)/90,perfect=err<=.12;let verdict=perfect?'¡Amarre perfecto!':err<=.45?'¡Casi!':err<=1.15?'Buen intento.':state.x<targetX?'Te quedaste corto.':'Te pasaste.';$('verdict').textContent=verdict;$('distance').textContent=err.toFixed(2);$('side').textContent=state.x<targetX?'Te faltaron '+err.toFixed(2)+' m.':'Te pasaste '+err.toFixed(2)+' m.';if(perfect)$('side').textContent='La dejaste prácticamente clavada.';if(best===null||err<best){best=err;try{localStorage.setItem('el-amarre-perfecto-best',String(best))}catch{}}$('best').textContent='MEJOR · '+best.toFixed(2)+' M';$('ready').hidden=true;$('result').hidden=false;$('scene-label').textContent=verdict.toUpperCase()+' · '+err.toFixed(2)+' M';$('action').disabled=false;tone(perfect);try{window.goatcounter?.count?.({path:'amarre-completado',title:'Amarre completado',event:true,no_session:true})}catch{}}
function path(points,fill){ctx.beginPath();ctx.moveTo(...points[0]);points.slice(1).forEach(p=>ctx.lineTo(...p));ctx.closePath();ctx.fillStyle=fill;ctx.fill()}
function boat(x,y){ctx.save();ctx.translate(x,y);ctx.fillStyle='rgba(22,65,66,.16)';ctx.beginPath();ctx.ellipse(0,30,60,9,0,0,Math.PI*2);ctx.fill();path([[-58,0],[58,0],[37,29],[-40,29]],'#f4ead8');ctx.strokeStyle='#315d5b';ctx.lineWidth=4;ctx.stroke();ctx.fillStyle='#bd6b50';ctx.fillRect(-15,-31,34,31);ctx.fillStyle='#244c4d';ctx.fillRect(-2,-44,4,44);ctx.restore()}
function draw(now){ctx.clearRect(0,0,W,H);let sky=ctx.createLinearGradient(0,0,0,480);sky.addColorStop(0,'#e9eee7');sky.addColorStop(1,'#eee4d3');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(224,177,106,.3)';ctx.beginPath();ctx.arc(820,125,68,0,Math.PI*2);ctx.fill();path([[0,335],[150,295],[270,330],[405,280],[545,330],[700,295],[840,330],[1000,285],[1000,410],[0,410]],'#9fb7a9');let sea=ctx.createLinearGradient(0,390,0,H);sea.addColorStop(0,'#6faaa2');sea.addColorStop(1,'#397b79');ctx.fillStyle=sea;ctx.fillRect(0,390,W,H-390);
ctx.strokeStyle='rgba(235,245,238,.35)';ctx.lineWidth=3;for(let y=445;y<760;y+=62){ctx.beginPath();for(let x=0;x<=W;x+=20){let yy=y+Math.sin(x*.018+now*.0012)*5;x?ctx.lineTo(x,yy):ctx.moveTo(x,yy)}ctx.stroke()}
ctx.fillStyle='#d7c09b';ctx.fillRect(targetX+70,395,210,250);ctx.fillStyle='#b79568';for(let y=420;y<640;y+=42)ctx.fillRect(targetX+78,y,194,5);ctx.strokeStyle='#f5ead4';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(targetX,500);ctx.lineTo(targetX,660);ctx.stroke();ctx.fillStyle='#f5ead4';ctx.beginPath();ctx.arc(targetX,500,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#b75a42';ctx.beginPath();ctx.arc(targetX,610,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f4ead8';ctx.beginPath();ctx.arc(targetX,610,8,0,Math.PI*2);ctx.fill();
if(phase==='ready'){let dt=Math.min(.032,(now-state.start)/1000);state.start=now;state.x+=state.v*dt;if(state.x>targetX+170){state.x=120}}else if(phase==='coast'){let dt=Math.min(.032,(now-state.cutAt)/1000);state.cutAt=now;state.v=Math.max(0,state.v-58*dt);state.x+=(state.v+state.drift)*dt;if(state.v<=1)finish()}
boat(state.x,585);requestAnimationFrame(draw)}
$('action').onclick=cut;$('scene').onclick=cut;$('again').onclick=newRound;document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&phase==='ready'){e.preventDefault();cut()}});
$('sound').onclick=()=>{audioOn=!audioOn;$('sound').setAttribute('aria-pressed',String(audioOn));$('sound-label').textContent=audioOn?'ON':'OFF';$('sound-icon').textContent=audioOn?'◖))':'◖̸'};
$('bookmark').onclick=()=>{$('bookmark-text').textContent=/iPhone|iPad/i.test(navigator.userAgent)?'En Safari, pulsa Compartir y elige «Añadir a favoritos».':'Pulsa Ctrl+D (Windows/Linux), ⌘+D (Mac) o usa el menú del navegador para guardar el juego.';$('bookmark-dialog').showModal()};
newRound();requestAnimationFrame(draw);